yarnPath: .yarn/releases/yarn-3.1.1.cjs
logFilters:
  - code: YN0061
    level: discard
  - code: YN0032
    level: discard
  - code: YN0013
    level: discard

networkConcurrency: 100

nodeLinker: node-modules

